name: flutter_bluetooth_serial_example
version: 0.2.2
description: Flutter Bluetooth Project

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.3.0
  scoped_model: ^1.0.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../

flutter:
  uses-material-design: true
